"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
ratio = [2, 4, 3]
linemode = "mtime"

[input]
cd_title = "cd:"
cd_origin = "bottom-left"
cd_offset = [0, 2, 50, 3]

[opener]
zth = [{ run = 'zathura "$@"', orphan = true }]

[open]
prepend_rules = [{ name = "*.pdf", use = ["zth"] }]
